apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyperdx.apiKey.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: hyperdx 
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  api-key: {{ include "common.secrets.passwords.manage" (dict "secret" (include "hyperdx.apiKey.secretName" .) "key" "api-key" "providedValues" (list "apiKey") "context" $) }}
